<?php

declare(strict_types=1);

return [
    [
        'class' => Apn\AmiClient\Protocol\Ping::class,
        'name' => 'Ping',
        'kind' => 'single',
        'enabled' => true,
        'required_params' => [],
        'params' => [],
        'completion' => [
            'timeout_ms' => 2000,
            'terminal_events' => [],
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\Command::class,
        'name' => 'Command',
        'kind' => 'follows',
        'enabled' => true,
        'required_params' => ['command'],
        'params' => ['command' => 'core show version'],
        'completion' => [
            'timeout_ms' => 3000,
            'terminal_events' => [],
            'follows_terminator' => '--END COMMAND--',
            'max_output_bytes' => 1048576,
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\PJSIPShowEndpoints::class,
        'name' => 'PJSIPShowEndpoints',
        'kind' => 'event_list',
        'enabled' => true,
        'required_params' => [],
        'params' => [],
        'completion' => [
            'timeout_ms' => 5000,
            'terminal_events' => ['EndpointListComplete'],
            'event_list_complete' => true,
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\PJSIPShowEndpoint::class,
        'name' => 'PJSIPShowEndpoint',
        'kind' => 'event_list',
        'enabled' => true,
        'required_params' => ['endpoint'],
        'params' => ['endpoint' => '__DISCOVERED_ENDPOINT__'],
        'completion' => [
            'timeout_ms' => 5000,
            'terminal_events' => ['EndpointDetailComplete'],
            'event_list_complete' => true,
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\QueueSummary::class,
        'name' => 'QueueSummary',
        'kind' => 'event_list',
        'enabled' => true,
        'required_params' => [],
        'params' => [],
        'completion' => [
            'timeout_ms' => 5000,
            'terminal_events' => ['QueueSummaryComplete'],
            'event_list_complete' => true,
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\QueueStatus::class,
        'name' => 'QueueStatus',
        'kind' => 'event_list',
        'enabled' => true,
        'required_params' => [],
        'params' => [],
        'completion' => [
            'timeout_ms' => 5000,
            'terminal_events' => ['QueueStatusComplete'],
            'event_list_complete' => true,
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\GetVar::class,
        'name' => 'GetVar',
        'kind' => 'single',
        'enabled' => false,
        'skip_reason' => 'Requires environment-specific variable/channel values.',
        'required_params' => ['variable'],
        'params' => ['variable' => 'FOO'],
        'completion' => [
            'timeout_ms' => 2000,
            'terminal_events' => [],
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\SetVar::class,
        'name' => 'SetVar',
        'kind' => 'single',
        'enabled' => false,
        'skip_reason' => 'Write action is disabled by default for real PBX validation.',
        'required_params' => ['variable', 'value'],
        'params' => ['variable' => 'FOO', 'value' => 'BAR'],
        'completion' => [
            'timeout_ms' => 2000,
            'terminal_events' => [],
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\Hangup::class,
        'name' => 'Hangup',
        'kind' => 'single',
        'enabled' => false,
        'skip_reason' => 'Potentially disruptive action; channel target is environment-specific.',
        'required_params' => ['channel'],
        'params' => ['channel' => 'PJSIP/100-00000001'],
        'completion' => [
            'timeout_ms' => 2000,
            'terminal_events' => [],
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\Originate::class,
        'name' => 'Originate',
        'kind' => 'single',
        'enabled' => false,
        'skip_reason' => 'Potentially disruptive call initiation action; disabled by default.',
        'required_params' => ['channel'],
        'params' => ['channel' => 'PJSIP/100'],
        'completion' => [
            'timeout_ms' => 5000,
            'terminal_events' => [],
        ],
    ],
    [
        'class' => Apn\AmiClient\Protocol\Redirect::class,
        'name' => 'Redirect',
        'kind' => 'single',
        'enabled' => false,
        'skip_reason' => 'Potentially disruptive active-call action; disabled by default.',
        'required_params' => ['channel', 'exten', 'context', 'priority'],
        'params' => ['channel' => 'PJSIP/100-00000001', 'exten' => '100', 'context' => 'default', 'priority' => 1],
        'completion' => [
            'timeout_ms' => 3000,
            'terminal_events' => [],
        ],
    ],
];
